### ISSUE TITLE
Toiminnallisuudet (TODO)

### ISSUE THREAD

**Issue by Bizhop** [Bizhop/jassu#3]
PRIO1

- [x] valtit/pamput/jokerit
- [x] pelin voittajan määritys

PRIO2

- [x] nosto
- [x] yhteinen
- [x] väkinäinen
- [x] hakki
- [x] valtin asetus
- [x] toinen pamppu nostaessa

PRIO3

- [x] pelin viejän merkintä
- [x] pelaamaton kierros (viitenä)
- [x] pelistä poistuminen (kolme pistettä täynnä)
- [x] pelin tallennus
- [x] pelin poisto
- [x] pelaajan nickname
- [x] valttimaa kuvana
- [x] ajettu maa
- [x] pakkaan meno
- [x] noston pitäisi tyhjätä käsikortit

PRIO4

- [x] pisteenlasku
- [x] puheet

**Comment by Wilsko** [comment]
Pelattiin Eemin ja Elsan kanssa muutama peli. Ei havaittu bugeja. 
Ehdotuksia:
Pelaajille Nicknamet jotka näytetään pelissä
Yhteisissä noston toinen kortti toiminnallisuuksiin mukaan
Valttimaa kuvana
Ajettu maa voisi nousta jotenkin esiin, helpottaisi hieman seuraamista 
Pelivuoro vilkutuksena tms.  (Toisaalta: "LYÖ JO" ja "KENEN VUORO" kuuluu peliin)
Muutama virhelyönti tuli, pitäisikö voida perua tai peli tarkistaisi

Terveisin I, E, E

**Comment by Bizhop** [comment]
Minimum lovable product (MLP) pitäis nyt olla kasassa, katsotaas noita parannuksia seuraavaksi :)

**Comment by Wilsko** [comment]
Keskusteltiin vähän aikaa pelin jälkeen Alapon ja Askon kanssa. 

- kun kaikki pelaajat on poistettu, pelin eteneminen seuraavaan on epäselvää. Paras tapa tuntui olevan päänäytön kautta.
- vanhan pelin viimeiset kortit näkyvät kun palataan peliin uudelleen
- toinen nostokortti voisi näkyä haamuna
- spekuloitiiin väärin pelaamisesta ja vahinkolyönneista. Virhelyönnistä voisi antaa huomautuksen "Oletko varma"
- viimeisen lyödyn kortin peruutus voisi myös toimia vahinkolyöntien korjaamiseeen.
- Pelin erikoisuuden, eli pietin kolmen kortin jälkeen voisi myös toteuttaa tulevaisuudessa kunhan puheet ja pistelasku toimivat. Se on "maukas lisä peliin"

Terveisin W,A,A

**Comment by Wilsko** [comment]
Askoa tuntui myös koodi kiinnostavan. Oli lukenut koronavilkun koodia kolme päivää. Voisiko antaa gihubiin luvat?

**Comment by Wilsko** [comment]
Katsopa myös uuden pelin käynnistyksessä vanhojen siivous. Otin ohjeita varten screenshotteja (ihan ei taidot riittänyt vielä wikin käyttöön). Huomasin että myös uuden pelin luonnissa ruudulla näkyi Alapon ja askon kanssa pelatun vanhan pelin kortit.

**Comment by Bizhop** [comment]
Tässähän niitä parannuksia taas tulloo
